//
// Created by Ralf on 2017/11/30.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include<jni.h>

extern "C" {
/*
 * Class:     com_example_ralf_myjnitest_JniUtil
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ralf_myjnitest_JniUtil_getStrFromJni
  (JNIEnv *env, jclass jcls){

    const char* ch = "String From JNI";
    return env->NewStringUTF(ch);

  }
 }

