/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ralf_cmake_JniActivity */

#ifndef _Included_com_example_ralf_cmake_JniActivity
#define _Included_com_example_ralf_cmake_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ralf_cmake_JniActivity
 * Method:    getContentFromJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ralf_cmake_JniActivity_getContentFromJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ralf_cmake_JniActivity
 * Method:    callJavaMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ralf_cmake_JniActivity_callJavaMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ralf_cmake_JniActivity
 * Method:    callJavaStaticMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ralf_cmake_JniActivity_callJavaStaticMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
